/*!
 * reveal.js Zoom plugin
 */
const Plugin={id:"zoom",init:function(e){e.getRevealElement().addEventListener("mousedown",(function(t){var o=/Linux/.test(window.navigator.platform)?"ctrl":"alt",n=(e.getConfig().zoomKey?e.getConfig().zoomKey:o)+"Key",i=e.getConfig().zoomLevel?e.getConfig().zoomLevel:2;t[n]&&!e.isOverview()&&(t.preventDefault(),zoom.to({x:t.clientX,y:t.clientY,scale:i,pan:!1}))}))},destroy:()=>{zoom.reset()}};export default()=>Plugin
/*!
 * zoom.js 0.3 (modified for use with reveal.js)
 * http://lab.hakim.se/zoom-js
 * MIT licensed
 *
 * Copyright (C) 2011-2014 Hakim El Hattab, http://hakim.se
 */;var zoom=function(){function e(e,t){var i=o();if(e.width=e.width||1,e.height=e.height||1,e.x-=(window.innerWidth-e.width*t)/2,e.y-=(window.innerHeight-e.height*t)/2,c)if(1===t)document.body.style.transform="";else{var d=i.x+"px "+i.y+"px",l="translate("+-e.x+"px,"+-e.y+"px) scale("+t+")";document.body.style.transformOrigin=d,document.body.style.transform=l}else 1===t?(document.body.style.position="",document.body.style.left="",document.body.style.top="",document.body.style.width="",document.body.style.height="",document.body.style.zoom=""):(document.body.style.position="relative",document.body.style.left=-(i.x+e.x)/t+"px",document.body.style.top=-(i.y+e.y)/t+"px",document.body.style.width=100*t+"%",document.body.style.height=100*t+"%",document.body.style.zoom=t);n=t,document.documentElement.classList&&(1!==n?document.documentElement.classList.add("zoomed"):document.documentElement.classList.remove("zoomed"))}function t(){var e=.12,t=window.innerWidth*e,l=window.innerHeight*e,s=o();d<l?window.scroll(s.x,s.y-14/n*(1-d/l)):d>window.innerHeight-l&&window.scroll(s.x,s.y+(1-(window.innerHeight-d)/l)*(14/n)),i<t?window.scroll(s.x-14/n*(1-i/t),s.y):i>window.innerWidth-t&&window.scroll(s.x+(1-(window.innerWidth-i)/t)*(14/n),s.y)}function o(){return{x:void 0!==window.scrollX?window.scrollX:window.pageXOffset,y:void 0!==window.scrollY?window.scrollY:window.pageYOffset}}var n=1,i=0,d=0,l=-1,s=-1,c="transform"in document.body.style;return c&&(document.body.style.transition="transform 0.8s ease"),document.addEventListener("keyup",(function(e){1!==n&&27===e.keyCode&&zoom.out()})),document.addEventListener("mousemove",(function(e){1!==n&&(i=e.clientX,d=e.clientY)})),{to:function(o){if(1!==n)zoom.out();else{if(o.x=o.x||0,o.y=o.y||0,o.element){var i=20,d=o.element.getBoundingClientRect();o.x=d.left-i,o.y=d.top-i,o.width=d.width+2*i,o.height=d.height+2*i}void 0!==o.width&&void 0!==o.height&&(o.scale=Math.max(Math.min(window.innerWidth/o.width,window.innerHeight/o.height),1)),o.scale>1&&(o.x*=o.scale,o.y*=o.scale,e(o,o.scale),!1!==o.pan&&(l=setTimeout((function(){s=setInterval(t,1e3/60)}),800)))}},out:function(){clearTimeout(l),clearInterval(s),e({x:0,y:0},1),n=1},magnify:function(e){this.to(e)},reset:function(){this.out()},zoomLevel:function(){return n}}}();