/*!
 * reveal.js Zoom plugin
 */
const e={id:"zoom",init:function(e){e.getRevealElement().addEventListener("mousedown",(function(t){var n=/Linux/.test(window.navigator.platform)?"ctrl":"alt",i=(e.getConfig().zoomKey?e.getConfig().zoomKey:n)+"Key",d=e.getConfig().zoomLevel?e.getConfig().zoomLevel:2;t[i]&&!e.isOverview()&&(t.preventDefault(),o.to({x:t.clientX,y:t.clientY,scale:d,pan:!1}))}))},destroy:()=>{o.reset()}};var t=()=>e,o=function(){function e(e,t){var o=n();if(e.width=e.width||1,e.height=e.height||1,e.x-=(window.innerWidth-e.width*t)/2,e.y-=(window.innerHeight-e.height*t)/2,r)if(1===t)document.body.style.transform="";else{var d=o.x+"px "+o.y+"px",l="translate("+-e.x+"px,"+-e.y+"px) scale("+t+")";document.body.style.transformOrigin=d,document.body.style.transform=l}else 1===t?(document.body.style.position="",document.body.style.left="",document.body.style.top="",document.body.style.width="",document.body.style.height="",document.body.style.zoom=""):(document.body.style.position="relative",document.body.style.left=-(o.x+e.x)/t+"px",document.body.style.top=-(o.y+e.y)/t+"px",document.body.style.width=100*t+"%",document.body.style.height=100*t+"%",document.body.style.zoom=t);i=t,document.documentElement.classList&&(1!==i?document.documentElement.classList.add("zoomed"):document.documentElement.classList.remove("zoomed"))}function t(){var e=.12*window.innerWidth,t=.12*window.innerHeight,o=n();l<t?window.scroll(o.x,o.y-14/i*(1-l/t)):l>window.innerHeight-t&&window.scroll(o.x,o.y+(1-(window.innerHeight-l)/t)*(14/i)),d<e?window.scroll(o.x-14/i*(1-d/e),o.y):d>window.innerWidth-e&&window.scroll(o.x+(1-(window.innerWidth-d)/e)*(14/i),o.y)}function n(){return{x:void 0!==window.scrollX?window.scrollX:window.pageXOffset,y:void 0!==window.scrollY?window.scrollY:window.pageYOffset}}var i=1,d=0,l=0,s=-1,c=-1,r="transform"in document.body.style;return r&&(document.body.style.transition="transform 0.8s ease"),document.addEventListener("keyup",(function(e){1!==i&&27===e.keyCode&&o.out()})),document.addEventListener("mousemove",(function(e){1!==i&&(d=e.clientX,l=e.clientY)})),{to:function(n){if(1!==i)o.out();else{if(n.x=n.x||0,n.y=n.y||0,n.element){var d=n.element.getBoundingClientRect();n.x=d.left-20,n.y=d.top-20,n.width=d.width+40,n.height=d.height+40}void 0!==n.width&&void 0!==n.height&&(n.scale=Math.max(Math.min(window.innerWidth/n.width,window.innerHeight/n.height),1)),n.scale>1&&(n.x*=n.scale,n.y*=n.scale,e(n,n.scale),!1!==n.pan&&(s=setTimeout((function(){c=setInterval(t,1e3/60)}),800)))}},out:function(){clearTimeout(s),clearInterval(c),e({x:0,y:0},1),i=1},magnify:function(e){this.to(e)},reset:function(){this.out()},zoomLevel:function(){return i}}}();
/*!
 * zoom.js 0.3 (modified for use with reveal.js)
 * http://lab.hakim.se/zoom-js
 * MIT licensed
 *
 * Copyright (C) 2011-2014 Hakim El Hattab, http://hakim.se
 */export{t as default};